"""empty message

Revision ID: 1522207f3c7b
Revises: d0fbaa0f5cac
Create Date: 2024-02-27 15:33:56.753857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1522207f3c7b'
down_revision = 'd0fbaa0f5cac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaksi_penjemputan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tanggal_transaksi', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaksi_penjemputan', schema=None) as batch_op:
        batch_op.drop_column('tanggal_transaksi')

    # ### end Alembic commands ###
