"""empty message

Revision ID: 3799c4b15972
Revises: f9a5ecb5225e
Create Date: 2024-02-07 15:39:50.856543

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3799c4b15972'
down_revision = 'f9a5ecb5225e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pengguna', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nama_pelanggan', sa.String(length=100), nullable=False))
        batch_op.drop_column('nama_pelanngan')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pengguna', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nama_pelanngan', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('nama_pelanggan')

    # ### end Alembic commands ###
