"""empty message

Revision ID: 77e617160fda
Revises: e360dd46fe1a
Create Date: 2024-02-27 20:13:17.649027

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '77e617160fda'
down_revision = 'e360dd46fe1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaksi_penjemputan', schema=None) as batch_op:
        batch_op.alter_column('id_ekspedisi',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaksi_penjemputan', schema=None) as batch_op:
        batch_op.alter_column('id_ekspedisi',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    # ### end Alembic commands ###
