"""empty message

Revision ID: cafac1d3c68e
Revises: 
Create Date: 2024-03-07 11:55:12.468215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cafac1d3c68e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ekspedisi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_ekspedisi', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kupon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_kupon', sa.String(length=100), nullable=False),
    sa.Column('harga_kupon', sa.Integer(), nullable=False),
    sa.Column('gambar_kupon', sa.String(length=100), nullable=False),
    sa.Column('jumlah_kupon', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('limbah_elektronik',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_limbah', sa.String(length=100), nullable=False),
    sa.Column('gambar_limbah', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lokasi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_lokasi', sa.String(length=100), nullable=False),
    sa.Column('alamat_lokasi', sa.String(length=100), nullable=False),
    sa.Column('waktu_buka', sa.DateTime(), nullable=False),
    sa.Column('waktu_tutup', sa.DateTime(), nullable=False),
    sa.Column('gambar_lokasi', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pengguna',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_pengguna', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('nomor_telepon', sa.String(length=20), nullable=False),
    sa.Column('foto_profil', sa.String(length=100), nullable=True),
    sa.Column('alamat', sa.String(length=100), nullable=True),
    sa.Column('poin', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nomor_telepon'),
    sa.UniqueConstraint('username')
    )
    op.create_table('redeem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_pengguna', sa.Integer(), nullable=False),
    sa.Column('id_kupon', sa.Integer(), nullable=False),
    sa.Column('waktu_ditukar', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_kupon'], ['kupon.id'], ),
    sa.ForeignKeyConstraint(['id_pengguna'], ['pengguna.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaksi_penjemputan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_pengguna', sa.Integer(), nullable=False),
    sa.Column('id_ekspedisi', sa.Integer(), nullable=True),
    sa.Column('id_lokasi', sa.Integer(), nullable=True),
    sa.Column('berat_limbah', sa.Integer(), nullable=False),
    sa.Column('tanggal_transaksi', sa.DateTime(), nullable=False),
    sa.Column('status_transaksi', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['id_ekspedisi'], ['ekspedisi.id'], ),
    sa.ForeignKeyConstraint(['id_lokasi'], ['lokasi.id'], ),
    sa.ForeignKeyConstraint(['id_pengguna'], ['pengguna.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaksi_penjemputan')
    op.drop_table('redeem')
    op.drop_table('pengguna')
    op.drop_table('lokasi')
    op.drop_table('limbah_elektronik')
    op.drop_table('kupon')
    op.drop_table('ekspedisi')
    # ### end Alembic commands ###
