"""empty message

Revision ID: cedcce12d196
Revises: 
Create Date: 2024-03-09 15:23:00.789839

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cedcce12d196'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('redeem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_pengguna', sa.Integer(), nullable=False),
    sa.Column('id_kupon', sa.Integer(), nullable=False),
    sa.Column('waktu_ditukar', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_kupon'], ['kupon.id'], ),
    sa.ForeignKeyConstraint(['id_pengguna'], ['pengguna.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaksi_penjemputan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tanggal_transaksi', sa.DateTime(), nullable=False))
        batch_op.alter_column('id_ekspedisi',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('id_lokasi',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaksi_penjemputan', schema=None) as batch_op:
        batch_op.alter_column('id_lokasi',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('id_ekspedisi',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.drop_column('tanggal_transaksi')

    op.drop_table('redeem')
    # ### end Alembic commands ###
