"""empty message

Revision ID: d0fbaa0f5cac
Revises: 651d1910b11d
Create Date: 2024-02-15 16:46:01.274608

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd0fbaa0f5cac'
down_revision = '651d1910b11d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pengguna', schema=None) as batch_op:
        batch_op.alter_column('alamat',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pengguna', schema=None) as batch_op:
        batch_op.alter_column('alamat',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
