"""empty message

Revision ID: e360dd46fe1a
Revises: 1522207f3c7b
Create Date: 2024-02-27 20:12:00.644214

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e360dd46fe1a'
down_revision = '1522207f3c7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaksi_penjemputan', schema=None) as batch_op:
        batch_op.alter_column('id_lokasi',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaksi_penjemputan', schema=None) as batch_op:
        batch_op.alter_column('id_lokasi',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    # ### end Alembic commands ###
